Nombre_producto=["Nintendo Switch",
    "PlayStation 5",
    "Xbox Series X",
    "PC Gamer",
    "Control para Xbox One",
    "Control para PlayStation 4",
    "Nintendo Switch Pro Controller",
    "Cámara para PlayStation 5",
    "Nintendo Switch Lite",
    "Xbox Series S",
    "PlayStation 4",
    "Xbox One",
    "Nintendo 3DS",
    "PlayStation VR",
    "Xbox One S",
    "Nintendo Switch Dock",
    "Raspberry Pi para emuladores",
    "GameCube Controller Adapter para Nintendo Switch",
    "Oculus Quest 2",
    "Nintendo Entertainment System: NES Classic Edition",
    "Super Nintendo Entertainment System: SNES Classic Edition",
    "Xbox Wireless Adapter para Windows",
    "Adaptador de corriente para Nintendo Switch",
    "Adaptador de corriente para PlayStation 4",
    "Adaptador de corriente para Xbox One",
    "Adaptador de corriente para Nintendo 3DS",
    "Cable HDMI para Nintendo Switch",
    "Cable HDMI para PlayStation 4",
    "Cable HDMI para Xbox One",
    "Cable HDMI para Nintendo 3DS",
    "Cable de carga USB para Nintendo Switch",
    "Cable de carga USB para PlayStation 4",
    "Cable de carga USB para Xbox One",
    "Cable de carga USB para Nintendo 3DS",
    "Cable Ethernet para PlayStation 4",
    "Cable Ethernet para Xbox One",
    "Tarjeta de memoria microSD para Nintendo Switch",
    "Tarjeta de memoria para PlayStation 4",
    "Tarjeta de memoria para Xbox One",
    "Tarjeta de memoria para Nintendo 3DS",
    "Juego Mario Kart 8 Deluxe para Nintendo Switch",
    "Juego The Legend of Zelda: Breath of the Wild para Nintendo Switch",
    "Juego Super Mario Odyssey para Nintendo Switch",
    "Juego Animal Crossing: New Horizons para Nintendo Switch",
    "Juego Super Smash Bros. Ultimate para Nintendo Switch",
    "Juego Splatoon 2 para Nintendo Switch",
    "Juego Minecraft para Nintendo Switch",
    "Juego Pokémon Sword para Nintendo Switch",
    "Juego Pokémon Shield para Nintendo Switch",
    "Juego Ring Fit Adventure para Nintendo Switch",
    "Juego Super Mario 3D World + Bowser's Fury para Nintendo Switch",
    "Juego Spider-Man: Miles Morales para PlayStation 5",
    "Juego Demon's Souls para PlayStation 5",
    "Juego Ratchet & Clank: Rift Apart para PlayStation 5",
    "Juego Returnal para PlayStation 5",
    "Juego Horizon Forbidden West para PlayStation 5",
    "Juego God of War Ragnarok para PlayStation 5",
    "Juego Halo Infinite para Xbox Series X",
    "Juego Forza Horizon 5 para Xbox Series X",
    "Juego Fable para Xbox Series X",
    "Juego Senua's Saga: Hellblade II para Xbox Series X",
    "Juego Starfield para Xbox Series X",
    "Juego The Elder Scrolls VI para Xbox Series X",
    "Juego Cyberpunk 2077 para PC",
    "Juego Grand Theft Auto V para PC",
    "Juego Red Dead Redemption 2 para PC",
    "Juego Fortnite para PC",
    "Juego Overwatch para PC",
    "Juego League of Legends para PC",
    "Juego Valorant para PC"]

